name: RSS Update
on:
  status
  #schedule:
  #  - cron: '10 * * * *'
jobs:
  ruby:
    if: github.event.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
  update_feed_ini:
    name: Update Feed.ini
    runs-on: ubuntu-latest
    steps:
      - run: pluto update Feed.ini
  create_post:
    name: Create Post
    runs-on: ubuntu-latest
    steps:
      - run: ruby planet.rb
