name: RSS Update
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: '10 * * * *'
jobs:
  RSS-Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Update Feed.ini
        run: pluto update Feed.ini    
      - name: Create Post
        run: ruby planet.rb
