name: RSS Update
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  #schedule:
  #  - cron: '10 * * * *'
jobs:
  RSS-Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: ls
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Update Feed.ini
        run: pluto update feed.ini    
      - name: Create Post
        run: ruby planet.rb
      - name: Adding Email
        run: git config --global user.email "automation@runthisboi.com"
      - name: Adding Username
        run: git config --global user.name "0x7C2f"
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh_url }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating RSS"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
